# Generated by Django 3.0.2 on 2020-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('serving_qty', models.IntegerField()),
                ('nf_calories', models.FloatField(default=0)),
                ('nf_total_fat', models.FloatField(default=0)),
                ('nf_total_carbohydrate', models.FloatField(default=0)),
                ('nf_protein', models.FloatField(default=0)),
                ('choices', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=20)),
            ],
        ),
    ]
